version: '3.8'

services:
  postgres-db:
    image: postgres:16.2
    container_name: postgresdb
    ports:
      - '5432:5432'
    networks:
      - student-api-network
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_SECRET}
    env_file:
      - .env
  students-api:
    container_name: students-api
    image: registry.github.com/akojimsg/java/students:v1.0.0-openjdk
    # build:
    #   context: .
    #   dockerfile: prod.Dockerfile
    #   args:
    #     - NODE_ENV=development
    depends_on:
      - postgres-db
    links:
      - postgres-db
    environment:
      POSTGRES_HOST: postgres-db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - student-api-network
networks:
  student-api-network:
    driver: bridge