version: '3.8'

services:
  students-api:
    container_name: students-api
    build:
       context: .
       dockerfile: Dockerfile
    image: ${MODULE}.students-api:${VERSION}
    env_file:
      - .env
    ports:
      - "5000:8080"
    networks:
      - student-api-network
networks:
  student-api-network:
    driver: bridge