# Datasource - postgres
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_SECRET}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
server:
  error:
    include-message: always
# Actuator
management:
  endpoints:
    web:
      exposure.include=*
  health:
    show-details: always
  info:
    env:
      enabled=true
#info
info:
  app:
    name: Student-Management-System
    description: A student management system rest application (monolith)
    version: 1.0.0
#application
application:
  settings:
    default:
      userinfo-secret: ${DEFAULT_USER_SECRET}
    #JWT Properties
    security:
      jwt:
        secret: ${JWT_SECRET}
        issuer: ${JWT_ISSUER}
        access-token:
          expiration: ${JWT_ACCESS_TOKEN_EXP}
        refresh-token:
          expiration: ${JWT_REFRESH_TOKEN_EXP}