name: Build
on:
  push:
    branches: ['develop']
jobs:
  build:
    name: Clean, Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
      - name: Install and configure EBS CLI
        uses: sparkplug-app/install-eb-cli-action@v1.1.1
      - name: Build SpringBoot deployment artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn -B clean package spring-boot:repackage
      - name: Deploy to Elastic Beanstalk
        run: eb init students-api-e1
      - run: eb use students-api-e1
      - env:
          AWS_PG_ENDPOINT: ${{ secrets.AWS_PG_ENDPOINT }}
          DB: ${{ secrets.DB }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SECRET: ${{ secrets.DB_SECRET }}
          DB_USER: ${{ secrets.DB_USER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: eb setenv POSTGRES_HOST=$AWS_PG_ENDPOINT DB=$DB DB_USER=$DB_USER DB_SECRET=$DB_SECRET DB_PORT=5432 JWT_SECRET=$JWT_SECRET SERVER_PORT=5000
      - run: eb deploy --version students-0.0.1-SNAPSHOT